### ISSUE TITLE
Speech generation fails for native MML

### ISSUE THREAD

**Issue by zorkow** [mathjax/MathJax-a11y#152] opened 2016-09-03 21:45 UTC
Switching on speech generation with native mathml renderer leads to a math processing error.
Happens on both FF and Safari.

**Comment by pkra** [comment] 2016-09-12 07:56
Is this not expected behavior? We never planned to support native MathML due to the bugs such as missing dataset APIs, missing maction implementaitons etc.

**Comment by pkra** [comment] 2017-07-11 20:24
As per F2F, closed as `wontfix`

**Closed by pkra** 2017-07-11 20:24 UTC
Labels: wontfix
